//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodawanie_przepisow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skladnik
    {
        public int Id_Skladniku { get; set; }
        public int Id_Przepisu { get; set; }
        public int Id_Produktu { get; set; }
        public string Gramatura { get; set; }
        public Nullable<int> Ilosc { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Przepis Przepis { get; set; }
    }
}
